# Generated by Django 4.2.3 on 2024-01-18 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_image_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispaly',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_images', to='gallery.image'),
        ),
        migrations.AddField(
            model_name='dispaly',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.image'),
        ),
    ]
