# Generated by Django 4.2.3 on 2024-01-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_dispaly_header_image_dispaly_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispaly',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
