# Generated by Django 4.2.3 on 2024-01-18 06:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_dispaly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispaly',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='-none', editable=False, populate_from='name'),
        ),
    ]
