# Generated by Django 4.2.3 on 2024-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_dispaly_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispaly',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='display_images', to='gallery.image'),
        ),
    ]
