# Generated by Django 4.2.3 on 2024-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_dispaly_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispaly',
            name='settings',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
