# Generated by Django 4.2.3 on 2024-02-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_dispaly_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dispaly',
            new_name='Display',
        ),
    ]
