# Generated by Django 4.2.3 on 2024-02-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_rename_dispaly_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispalyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.display')),
            ],
        ),
    ]
