# Generated by Django 4.2.3 on 2024-02-17 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_dispalykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispalykey',
            name='expire',
            field=models.DateField(default=datetime.date(2024, 5, 17)),
        ),
    ]
